### ISSUE TITLE
Chore: Add more demo data sources

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#1064]
## Description

Add more demo data sources to showcase querying multiple data sources at one.

Currently we have the `glaredb-demos` bucket that we can stick parquet, csv, etc files in. But we don't have anything showing off `CREATE EXTERNAL DATABASE ...`. It's probably easiest to set up Postgres and make a read only user.

**Comment by greyscaled** [comment]
Ideally someone can `SELECT * FROM <data-source>` and not have to set anything up.

- parquet files in GCS (`glaredb-demos`)
- publically accessible Postgres with some data
  - user with limited permissions
  - small data set

The idea is to not have to set up a data source, but the data source still needs to be connected. Could also use the table functions to lower friction.

Internally, we need to figure out which project the data will live in.

**Comment by greyscaled** [comment]
cc @f0ssel
