### ISSUE TITLE
Read from http endpoints

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#1098]
## Summary

E.g. `select * from read_url('https://huggingface.co/...')`

See https://huggingface.co/blog/hub-duckdb

**Comment by greyscaled** [comment]
Very excited for this one!

**Comment by universalmind303** [comment]
I wonder if we could do this and https://github.com/GlareDB/glaredb/issues/1100 by using [object_store](https://crates.io/crates/object_store/0.3.0).

**Comment by scsmithr** [comment]
Azure blob storage definitely will be easy with object_store (we're already using it for gcp and aws).

I did a quick attempt at http using object_store (https://github.com/GlareDB/glaredb/commit/0179e881d9315521a29ac1f4e5a02fc6b4e32d06) but came to realization that it probably wouldn't be a good fit here. It's geared towards webdav, and requires those http extensions for things like listing objects. I imagine there will be a lot of sites that don't support webdav (and I know huggingface doesn't).

For this use case, I think it'd be acceptable to not use object_store, and just write a simple implementation that accepts a list of partition urls to read from, and we make the requests ourselves. This will require that the user explicitly lists out the partitions, but I don't think that's terrible.

**Comment by universalmind303** [comment]
> This will require that the user explicitly lists out the partitions, but I don't think that's terrible.
so that'd end up being pretty similar to how duckdb has it implemented? 

```sql
SELECT * FROM parquet_scan(['https://domain.tld/file1.parquet', 'https://domain.tld/file2.parquet']);
```

I'd assume we'd also want to support pushdowns & other optimizations for supported file types _(parquet & arrow)_ if the http server supports range requests?

**Comment by scsmithr** [comment]
First iteration: Something that works.
