### ISSUE TITLE
Add credential database object

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#1126]
## Summary

Create new database object that can be used when accessing object storage.

### Specifications

Create

```sql
CREATE CREDENTIAL my_creds
PROVIDER aws
OPTIONS (access_key_id = '<access-key>', secret_access_key = '<secret>')
[COMMENT 'a comment'];
```

Drop

```sql
DROP CREDENTIAL [IF EXISTS] my_creds;
```

Usage (table creates)

```sql
CREATE EXTERNAL TABLE my_table
FROM s3
OPTIONS (credentials = my_creds, ...);
```

Usage (copy to)

```sql
COPY (SELECT * FROM glare_catalog.tables) 
TO 's3://sean-test-glaredb/test2.json'
OPTIONS (CREDENTIALS my_creds);
```

Usage (table func)
```sql
SELECT * FROM read_parquet('s3://...', my_creds);
```
(Note we don't have a `read_parquet` function yet.)

Like tunnel, credentials will be a top-level item and will live in its own unique namespace.

When resolving credentials during a table create, we’ll ensure that the data source type matches the credential type (e.g. `s3` tables should only allow `aws` credentials).

## Rationale

Definite

**Comment by vrongmeal** [comment]
Do we want credentials to be referred or once a datasource is created, they become static?

Basically, does a table refer to credentials and if the credentials are updated (altered), should the table be able to pick up the new credentials or when creating the table with credentials the values are saved in each table from the creds object?

To actually have any benefits of saving the creds reference, we need to have an `ALTER CREDENTIALS ...` statement, else it's pretty useless.

**Comment by vrongmeal** [comment]
I'm currently going with just copying creds from the object into tables/databases. We can change this later if we want.

**Comment by scsmithr** [comment]
Copying the creds is fine for now, but I'd like for us to move towards referencing them in the near term. 

> To actually have any benefits of saving the creds reference, we need to have an ALTER CREDENTIALS ... statement, else it's pretty useless.

As an alternative to this, we could have the ALTER TABLE/DATABASE command allow altering which credentials to use. So to update, you'd create a new credentials object, then run ALTER TABLE to point to that new creds object.

**Comment by vrongmeal** [comment]
> As an alternative to this, we could have the ALTER TABLE/DATABASE command allow altering which credentials to use. So to update, you'd create a new credentials object, then run ALTER TABLE to point to that new creds object.

We can still do this by just copying the creds.

I feel we should refer credentials and have an `ALTER CREDENTIALS ...` to implement this behaviour.
