### ISSUE TITLE
Support EXTERNAL TABLEs for deltalake

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#1127]
> This looks good — just a little comment.
> 
> Should add the `EXTERNAL TABLE` support as well.

I opted to not do that in this PR since I'm now sure how we want to handle this. Delta files are able to be accessed without a catalog (since they're just files in object storage). If we added EXTERNAL TABLE support, what would we do? Require that a catalog is provided, or just have the user specify the path to the file?

It's not clear to me what the best solution is here. I figured we'll learn more while we continue to flesh this out.

> You also mentioned connecting without "catalog". How does that work? A catalog is just a database, right?

The catalog in the case of deltalake just provides us the location of objects in some object store. The catalog isn't needed if the location of an object is known ahead of time, since all that's needed to read/modify a delta file is self-contained.

For example, the databricks deployment I have set up on AWS stores delta files in s3. Making the GET request for one of the tables will just return the table location in s3. I then use the credentials provided when actually access those objects in s3.

_Originally posted by @scsmithr in https://github.com/GlareDB/glaredb/issues/1119#issuecomment-1591138471_

**Comment by greyscaled** [comment]
`delta_scan` ?
