### ISSUE TITLE
Chore: Move metastore builtin types to sqlbuiltins crate

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#1128]
## Description

Move it.

I want to try to make it so that `metastore` is only imported by `glaredb`. All "client" stuff should be moved into `metastoreproto`, and all "builtin" stuff should be moved into `sqlbuiltins`.

## What This Enables

Clearer separation of concerns. Also makes it less likely to run into dependency cycles.

**Comment by f0ssel** [comment]
I love dependency cycles

**Comment by adhish20** [comment]
only sqlexec still depends on metastore
