### ISSUE TITLE
Chore: `--ignore-auth` for local development

### ISSUE THREAD

**Issue by greyscaled** [GlareDB/glaredb#1144]
## Description

I'm developing cloud against local glaredb

```
cargo run --bin glaredb server
```

and can't get past:

```
unsupported frontend message: PasswordMessage { password: "..." }
```

It's unfeasible for me to pass `--password` and `--user` in this scenario.

## What This Enables

DX

## Impacts

DX

**Comment by scsmithr** [comment]
Done in #1145
