### ISSUE TITLE
Implement `list_schemas`/`list_tables` for internal tables

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#1153]
## Summary

https://github.com/glaredb/glaredb/blob/c1362ac04d8882770ecc4b0eb20d577096287b67/crates/sqlbuiltins/src/functions.rs#L583

Grey is going to start running into some panics.

**Comment by greyscaled** [comment]
> Grey is going to start running into some panics.

I did, and currently I work around this by using the catalog for internal tables, and the functions for external ones.

**Comment by scsmithr** [comment]
Seems like this was done.
