### ISSUE TITLE
Actually drop native table contents

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#1166]
## Context

Currently tables just get dropped in the catalog:

https://github.com/glaredb/glaredb/blob/1f8db207dcbd1a0bbbc43873dfc9a25fc76a8c09/crates/sqlexec/src/context.rs#L412-L427

Now with native tables, dropping a table will orphan the data with no clear way of cleaning it up.

Something we could explore is an async job queue that just cleans this stuff up in the background. This would also provide some resiliency towards failures since we could retry jobs and not have it affect client operations.

## Impact

- Storage/billing related (see: #1155)

**Comment by scsmithr** [comment]
See #1167 for if we choose to go with the background job approach.

**Comment by universalmind303** [comment]
is this no longer blocked since https://github.com/GlareDB/glaredb/pull/1353
