### ISSUE TITLE
Add `delta_scan` function

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#1187]
## Summary

Similar to `csv_scan` and `parquet_scan`, just instead for reading delta tables. Initial pass will probably just be for local files, then follow on for gcs/s3.

**Comment by greyscaled** [comment]
- add support for gcs, s3 in the other `_scan` functions (handling credentials etc)
- then implement `delta_scan`

**Comment by greyscaled** [comment]
Do #1249 first or with this

**Comment by scsmithr** [comment]
This should no longer be blocked with @vrongmeal's creds works.
