### ISSUE TITLE
Add `json_scan` function

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#1196]
## Summary

Two options:

- One function can handle both a json array, and new line delimited json
- Or have separate functions: `json_scan` and `ndjson_scan`

**Comment by greyscaled** [comment]
Can we close https://github.com/GlareDB/glaredb/issues/421 in favour of this?

**Comment by scsmithr** [comment]
> Can we close #421 in favour of this?

Two different things. `json_scan` would be reading json from a file (or remote). The json funcs issue is for stuff like this: https://www.postgresql.org/docs/9.5/functions-json.html

**Comment by scsmithr** [comment]
Yeah `ndjson_scan` sounds good to me.
