### ISSUE TITLE
Python dependency breaks `glaredb` local use in `v0.0.16`

### ISSUE THREAD

**Issue by greyscaled** [GlareDB/glaredb#1197]
## Context

- glaredb: v0.0.16
- MacOS

We're developing Python bindings for `glaredb`. Unfortunately, this created a dependency on having Python headers and versions installed locally when using the binary locally.

## Expected

I can use the binary locally without Python dependencies

## Actual

I require specific Python installation

**Comment by universalmind303** [comment]
I can take a look at this one.

**Comment by universalmind303** [comment]
@greyscaled can you provide the build commands you were using? was it `cargo build` or `cargo xtask build`

**Comment by scsmithr** [comment]
Fixed with https://github.com/GlareDB/glaredb/pull/1198.

`cargo xtask build` is what builds the binaries (which internally just calls `cargo build --bin glaredb` with nothing special).
