### ISSUE TITLE
Allow configuring session to use remote metastore and storage in python bindings

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#1221]
## Summary

See https://github.com/GlareDB/cloud/issues/1611 for some rationale.

This should be configurable via arguments to `connect`, as well as through environment variables so that users don't need to configure anything when running inside a python compute engine.

**Comment by universalmind303** [comment]
going to actually hold off on this one for now, I think there's still some additional refinement needed to figure out how exactly we plan on communicating between the python client & remote server.

**Comment by scsmithr** [comment]
# Remote metastore/storage

The use case for this is being able to run `glaredb` locally, and connect it to
an instance running on glaredb cloud.

The ux might look something like this:

1. Start glaredb via `glaredb local --cloud <cloud-instance-name>` from the
   command line or `glaredb.connect(<cloud-instance-name>)` from python.
2. Get prompted to log in, or us some authentication mechanism (api keys,
   browser link, etc).
3. Be able to execute queries as you normally would with some of the execution
   being routed to the cloud instance.
   
# Execution break down

- When connecting, the local instance of glaredb will download a copy of the
  catalog.
- All query planning will be done locally. It will be assumed that executing
  scans against anything that's not a local data frame or file will be ran on
  the remote instance.
- The physical plan will be split into "local" and "remote" fragments. Remote
  fragments will be executed on the cloud instance, and local fragements will be
  executed locally.

# Infrastructure needs

None of the communication between the remote/local instances will be going
through pgsrv as that's postgres protocol specific, and there's no overlap
between that and what we're trying to do here.

So this means we'll likely add in an additional service with the following
endpoints:

- Retrieve catalog
- Execute physical plan fragment

Both endpoints should be authenticated (unsure if we want to use the existing
username/password stuff, or just go with api keys).

I'm also unsure what we want the protocol/serialization to look like. GRPC is
likely for transport, and then either datafusion proto or substrait for physical
plan serialization.

**Comment by greyscaled** [comment]
@universalmind303 is researching around the planning and what's possible with DF. This one is a blocker for the initiative on Cloud, so we need to figure out what's possible first before continuing elsewhere too far.

**Comment by universalmind303** [comment]
we create a new datasource that wraps the existing file & object store datasources. Check if it's local/remote & delegate accordingly. The implementation should be pretty easy, but it'll likely have a pretty big cascading effect on the existing code.

- implement new CloudExec for the various datasources we want to run in the cloud (cloudHttpExec, cloudS3Exec, ...). Or potentially a generic implementation instead. 
- implement new hybridExec that wraps the local & cloud ones & delegates accordingly.
- replace calls to existing datasources with new hybrid compatible sources

The join nodes will be pretty tricky, we'll have to do some checking to make sure both sides can & should be done on client or server & potentially some other optimizations as well. More discovery will likely be needed on the join & union implementations.

**Comment by greyscaled** [comment]
Split up per data source (serializing each one)?

**Comment by scsmithr** [comment]
An initial pass for this might actually be skipping the plan serialization, exposing metastore, and having a more generic auth mechanism with Cloud. So instead of having to send plans over the network, we just execute everything locally.

The flow on startup may look something like this:

1. (SQL) Username/password provided in `glaredb.connect`
2. In-process glaredb connects to Cloud to retrieve a service account (using the username/password)
3. In-process glaredb _also_ connects to metastore to retrieve the catalog (using the username/password)
4. Create local session using service account provided by Cloud for storage access, and an authenticate grpc connection to metastore.
   
Then once the session is created, we just resume execution as normal, and everything is executed locally.

This would also provide an opportunity to cleanup session initialization if we feel that's worthwhile.

**Comment by greyscaled** [comment]
https://github.com/GlareDB/glaredb/issues/1278 might necessitate the need to change how we create sessions. Python CE will need have needs like writing directly to storage.

**Comment by scsmithr** [comment]
Hybrid execution obviates this.
