### ISSUE TITLE
Chore: Keep py-glaredb and glaredb versions in sync

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#1223]
## Description

I think the only thing needed to release both at the same time is trigger python releases on 'v*' tags.

Also requires that we update `Cargo.toml` and `py-glaredb/Cargo.toml` at the same time.

**Comment by greyscaled** [comment]
Noted to update both cargos.

@scsmithr will a root `cargo build` suffice, or do we need a second command for `py-glared` ?
