### ISSUE TITLE
Support object storage for `*_scan` functions

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#1249]
## Summary

E.g. something like:
```
select * from parquet_scan('s3://bucket/path.parquet', access_key=..., secret=...)
```

Alternatively we should allow use of a credentials object:

```
create credentials my_creds ...

select * from parquet_scan('s3://bucket/path.parquet', my_creds)
```

**Comment by universalmind303** [comment]
@vrongmeal It looks like this has significant overlap with the work I'm doing in https://github.com/GlareDB/glaredb/pull/1262.
