### ISSUE TITLE
Unable to fetch table provider

### ISSUE THREAD

**Issue by greyscaled** [GlareDB/glaredb#1254]
## Context

- Local development (cloud)
- I created a table `public.ddd`
- I inserted some values
- I selected *
- I then refreshed the page
- I was never able to query again

## Expected

I'm able to query `select * from public.ddd`

## Actual

> Error during planning: Unable to fetch table provider for 'public.ddd': Failed to dispatch to table: Not a Delta table: No snapshot or version 0 found, perhaps memory://databases/00000000-0000-0000-0000-000000000000/tables/20001 is an empty dir?

## Impact

I can't use my native tables after re-connecting

**Comment by greyscaled** [comment]
This seems to only be happening in local dev

**Comment by scsmithr** [comment]
Do you happen to recall the create table statement you used? And has this happened multiple times?

**Comment by scsmithr** [comment]
This should be fixed now that in-memory stores for tables during dev are shared across sessions.
