### ISSUE TITLE
Physical plan fragment proxy

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#1278]
## Summary

we need a light server that can
- accept protobuf serialized physical plans
- execute the plan
- return an ipc stream of the execution result. 

The end goal will be to create a cloud execution node that will use this proxy internally.

**Comment by greyscaled** [comment]
Authn is still being worked out

**Comment by greyscaled** [comment]
We don't know the requirements for `cloud` yet.

Sean: We might be able to use the existing authn endpoint
Garrett: Would we do it as a sep port on pgsrv?
Sean + Cory: Sep service, lightweight, not speaking pg protocol

**Comment by greyscaled** [comment]
Looking into serializing logical plans (over physical plans)

**Comment by greyscaled** [comment]
Design doc in prog
