### ISSUE TITLE
Chore: set up proper dev environment for py-glaredb

### ISSUE THREAD

**Issue by universalmind303** [GlareDB/glaredb#1290]
## Description

set up proper dev environment for py-glaredb.
checklist 
- [ ] auto linting
- [ ] IDE module detection & typehints

probably a few other things like dev/optional dependencies as well. But I think auto linting/formatting & module detection for `glaredb` are the most important. 

## What This Enables

will make it easier for people to contribute.

**Comment by scsmithr** [comment]
What would it take to close this out? I'm not familiar with Python enough to know what tools/linters/etc we'll want to use. My workflow has been mostly run the python scripts and see if they work. I don't have any in-editor hints right now.

**Comment by universalmind303** [comment]
I'll take a look at this one. I think we can likely borrow some ideas from other pyo3 packages.

**Comment by universalmind303** [comment]
so `IDE module detection & typehints` is actually a bit more work. with other bindings libraries they will auto generate docs & type definitions for you. Unfortunately, that doesnt seem to be the case with pyo3. It seems like all other libraries have a thin python wrapper that exposes the type definitions. 

https://github.com/apache/arrow-ballista-python
https://github.com/apache/arrow-datafusion-python
https://github.com/pola-rs/polars

**Comment by universalmind303** [comment]
closed via https://github.com/GlareDB/glaredb/pull/1354
