### ISSUE TITLE
Allow scanning gzipped json files

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#1316]
## Summary

E.g. I want to run:

```
select * from ndjson_scan('https://huggingface.co/datasets/allenai/c4/resolve/main/en/c4-train.00000-of-01024.json.gz');
```

## Rationale

A lot of big data sets, incl public/OSS ones, are available in compressed formats.

Being able to reduce friction/steps makes the experience of working with glaredb on those sets much nicer

## Impact

None

**Comment by universalmind303** [comment]
@vrongmeal If you haven't started this one yet, I can take it on.
