### ISSUE TITLE
Disable using local datasource on the server

### ISSUE THREAD

**Issue by vrongmeal** [GlareDB/glaredb#1324]
## Context

The command `COPY my_table TO './local_path.csv'` would work and might overload the server. Similarly, a user can read a local file on the server which shouldn't be possible.

## Expected

Error when running local commands on the server.

## Actual

Command works as expected.

## Impact

Security concerns.

**Comment by eitsupi** [comment]
Hello. I'm having trouble setting up GlareDB for CI in PRQL/prql#3658.
The ability to read local files is definitely useful.
Could you consider a workaround such as allowing only certain directories like ClickHouse?
<https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#user_files_path>
