### ISSUE TITLE
Support updates

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#1351]
## Description

```
UPDATE table_name SET c1 ='hello', c2 = 'hello', WHERE c3 > 5; 
```

## Rationale

- Hels round out native tables
  - User ask
- Storage/billing related (see: #1155)

**Comment by greyscaled** [comment]
Marking as a high priority for similar reasons to #1352

**Comment by adhish20** [comment]
delta lake implementation : https://github.com/delta-io/delta-rs/pull/1390
