### ISSUE TITLE
Support deletes

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#1352]
## Description

```
DELETE FROM table_name WHERE a > 5;
```

## Rationale

- Hels round out native tables
  - User ask
- Storage/billing related (see: #1155)

**Comment by greyscaled** [comment]
Marking as high priority so as to make native tables more useful

**Comment by greyscaled** [comment]
Will require poking around delta lake lib. We need to see if they support it, if not write up reqs. Same with #1351

**Comment by adhish20** [comment]
delta lake implementation : https://github.com/delta-io/delta-rs/pull/1176
