### ISSUE TITLE
Add iceberg support

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#1358]
## Description

- Read only for now
- Parquet only (there's some avro stuff we'll need to figure out too)
- Initial pass should expose just an `iceberg_scan` function

## Rationale

https://twitter.com/tabulario/status/1682130385214513154

**Comment by greyscaled** [comment]
Moving in progress as per https://github.com/GlareDB/glaredb/pull/1382 and tweets :tada:
