### ISSUE TITLE
add --log-level to glaredb

### ISSUE THREAD

**Issue by universalmind303** [GlareDB/glaredb#1392]
## Description

It'd be nice to be able to specify the log level when running the server. should support [error,warn,info,debug,trace]

```sh
glaredb local --log-level trace
glaredb local --log-level error
```

## Rationale

makes it much easier to see relevant logs when running the server.

**Comment by scsmithr** [comment]
We have _some_ support for this with the `-v` (debug) and `-vv` (trace) flags
