### ISSUE TITLE
Chore: Discord channel structure

### ISSUE THREAD

**Issue by greyscaled** [GlareDB/glaredb#1394]
## Description

Right now we have 1 channel, plus an empty "Rules".

![Discord](https://github.com/GlareDB/glaredb/assets/11184711/63c40905-cc9d-418f-b3be-4ef667c2e9b5)

It might be nice if we had at least 2 channels:

- general
- announcements

But I could also see a few others:

- questions/support
- welcome

## What This Enables

Improved Discord community experience

## Impacts

Discord Administrator

**Comment by 0xf333** [comment]
# GlareDB Discord Server Idea (#1394)


<br>
This is to establish a collaborative and engaging platform for the project community; the idea is to facilitate project discussions, contributions, and support, while also offering spaces for off-topic interactions to keep the environment "chill".

<br>

## SERVER STRUCTURE

**Category: General**
- `# 👋 | welcome` : For welcoming users and pinning server rules.
- `# 📢 | announcements`: For important project updates.
- `# 💬 | general-chat`: For general discussions.

**Category: Project Discussion**
- `# 💾 | database-discussion`: For database project discussions.
- `# 👨‍💻 | development`: For development-related discussions.
- `# 🐞 | bug-reports`: For reporting software bugs.
- `# 🌟 | feature-requests`: For suggesting new features.

**Category: Contribution**
- `# 📝 | contribution-guidelines`: For contribution guidelines.
- `# 🔄 | pull-requests`: For discussing pull requests.
- `# 📚 | documentation`: For documentation discussions.

**Category: Support**
- `# 🔧 | installation-help`: For installation assistance.
- `# ❓ | usage-questions`: For software usage questions.
- `# 🔍 | troubleshooting`: For troubleshooting software issues.

**Category: Off-Topic**
- `# 🎲 | random`: For off-topic discussions.
- `# 😂 | fun-stuff`: For sharing fun contents and memes.

**Category: Admin**
- `# 🔒 | moderator-chat`: For moderator discussions.
- `# 📝 | server-feedback`: For server feedback and suggestions.

### Server mock-up sample

<img src="https://raw.githubusercontent.com/0xf333/img/main/server_mockup.png" alt="MEE6 Example" width="900"/>

<br>

## ADMIN TOOLS SUGGESTION

The seggestion here would be **MEE6** as a Discord bot for the server; it's offers a wide range of features that can help in moderating the server, for instance: 

### This could be used for users to open tickets

<img src="https://raw.githubusercontent.com/0xf333/img/main/tickets.png" alt="MEE6 Example" width="900"/>


### And this for community voting on project proposals 

<img src="https://raw.githubusercontent.com/0xf333/img/main/vote.png" alt="MEE6 Example" width="900"/>

**Comment by greyscaled** [comment]
tracked elsewhere
