### ISSUE TITLE
Org name as subdomain of host no longer works

### ISSUE THREAD

**Issue by greyscaled** [GlareDB/glaredb#1404]
## Context

My connection string in the format of:

```
org_name.host:6543/dp_name
```

no longer works, but this will work:

```
host:6543/org_id/dp_name
```

## Expected

Both work.

## Actual

Only the latter works

## Impact

Cloud dashboard

**Comment by scsmithr** [comment]
workin for me (new deployment, so not hitting possibility of the catalog issue)

<img width="1088" alt="Screenshot 2023-07-26 at 10 23 17 AM" src="https://github.com/GlareDB/glaredb/assets/4040560/74096d57-4851-4d9d-9b19-64367a171644">
