### ISSUE TITLE
Make connecting to remote clients easier via command line

### ISSUE THREAD

**Issue by universalmind303** [GlareDB/glaredb#1424]
## Description
[Clickhouse](https://clickhouse.com/docs/en/integrations/sql-clients/cli) makes it very simple to connect to a remote server. 

```sh
clickhouse-client --host HOSTNAME.clickhouse.cloud \
  --secure \
  --port 9440 \
  --user default \
  --password PASSWORD
  ```

  It'd be nice to do something similar when connecting to cloud
  ```sh
  glaredb client <... connection params>
```

This _may_ depend on https://github.com/GlareDB/glaredb/issues/1278, not entirely sure. 

## Rationale

It'll make it easier for local exploration on a cloud instance without having to use pgsrv.

**Comment by scsmithr** [comment]
We have the `--cloud-url` flag:

```
  -c, --cloud-url <CLOUD_URL>
          URL for connecting to a GlareDB Cloud deployment or self hosted server
```

Might be enough to close out this issue.
