### ISSUE TITLE
Chore: Use datafusion's SessionContext instead of SessionState

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#1432]
## Description

Currently we're using `SessionState`, however this has been a bit tricky to work with, in particular with mutating some of its fields (`ExecutionProps`). This has led to #1427 since we're unable to set the execution start time (which is used during optimizing `now` and related functions).

Working with `SessionState` directly was originally chosen for a few reasons:
- All fields were at one point public allowing us to set things directly (including the execution props).
- We don't need the additional functionality provided by `SessionContext` as we're doing a lot of that ourselves.

When switching to `SessionContext`, getting the state will be done through the `state` method. Internally this returns a cloned state with the execution props having the correct start time. Cloning isn't required for us since we execute queries sequentially, but there's no other way for us to set the appropriate execution start time.

## What This Enables

Fixes #1427

**Comment by vrongmeal** [comment]
https://github.com/GlareDB/glaredb/pull/1509#issuecomment-1668556107:

> TBH, not completely happy with this. I want to create another wrapper to handle everything related to the "execution of a query", basically one state for one execution. This works but creates a copy of the state each time. The only thing the copy has different is the query_execution_start_time, which we wanted.

**Comment by scsmithr** [comment]
This is done.
