### ISSUE TITLE
Investigate: Building 0.3.0 image failed the first time

### ISSUE THREAD

**Issue by greyscaled** [GlareDB/glaredb#1460]
## Context

It failed quickly (~48seconds)

https://github.com/GlareDB/glaredb/actions/runs/5739955754/job/15556727166#step:6:164

with:

> error[E0433]: failed to resolve: could not find `FsConfigCmd` in `types`
>    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rustix-0.38.5/src/backend/linux_raw/mount/syscalls.rs:214:27
>     |
> 214 |             super::types::FsConfigCmd::Create,
>     |                           ^^^^^^^^^^^ could not find `FsConfigCmd` in `types`
> 
> error[E0433]: failed to resolve: could not find `FsConfigCmd` in `types`
>    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rustix-0.38.5/src/backend/linux_raw/mount/syscalls.rs:228:27
>     |
> 228 |             super::types::FsConfigCmd::Reconfigure,
>     |                           ^^^^^^^^^^^ could not find `FsConfigCmd` in `types`
> 
>    Compiling serde_json v1.0.104
>    Compiling camino v1.1.6
>    Compiling crypto-common v0.1.6
> error[E0277]: the trait bound `reg::ArgReg<'_, A3>: From<MountFlagsArg>` is not satisfied
>    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rustix-0.38.5/src/backend/linux_raw/arch/mod.rs:258:17
>     |
> 258 |               $a3.into(),
>     |                   ^^^^ the trait `From<MountFlagsArg>` is not implemented for `reg::ArgReg<'_, A3>`
>     |
>    ::: /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rustix-0.38.5/src/backend/linux_raw/mount/syscalls.rs:23:13
>     |
> 23  |           ret(syscall_readonly!(
>     |  _____________-
> 24  | |             __NR_mount,
> 25  | |             source,
> 26  | |             target,
> ...   |
> 29  | |             data
> 30  | |         ))
>     | |_________- in this macro invocation
>     |
>     = help: the following other types implement trait `From<T>`:
>               <reg::ArgReg<'a, Num> as From<&'a CStr>>
>               <reg::ArgReg<'a, Num> as From<&'a mut MaybeUninit<T>>>
>               <reg::ArgReg<'a, Num> as From<&'a mut [MaybeUninit<T>]>>
>               <reg::ArgReg<'a, Num> as From<(backend::fs::types::Mode, backend::fs::types::FileType)>>
>               <reg::ArgReg<'a, Num> as From<*const T>>
>               <reg::ArgReg<'a, Num> as From<*mut T>>
>               <reg::ArgReg<'a, Num> as From<Advice>>
>               <reg::ArgReg<'a, Num> as From<BorrowedFd<'a>>>
>             and 18 others
>     = note: required for `MountFlagsArg` to implement `Into<reg::ArgReg<'_, A3>>`
>     = note: this error originates in the macro `syscall_readonly` (in Nightly builds, run with -Z macro-backtrace for more info)
> 
>    Compiling block-buffer v0.10.4
>    Compiling term_size v0.3.2

**Comment by scsmithr** [comment]
Specifically on `cargo install just`. Not sure why that would intermittently fail.

**Comment by sunfishcode** [comment]
This was a bug in rustix 0.38.5, which is now fixed in rustix 0.35.6.

**Comment by scsmithr** [comment]
🙏 Really appreciate the info and getting a fix out quickly.
