### ISSUE TITLE
Query1 Error during planning: Unable to fetch table provider for 'lineitem': Failed to find table for reference: lineitem

### ISSUE THREAD

**Issue by djouallah** [GlareDB/glaredb#1466]
reproducible notebook

https://colab.research.google.com/drive/1A4ke71RehvbUdUMJjcsZqpswH9t5s_fD#scrollTo=xqkoz0jSepzL

**Comment by scsmithr** [comment]
Looking at this right now, appreciate the notebook

**Comment by scsmithr** [comment]
Got it running:
<img width="1484" alt="Screenshot 2023-08-02 at 9 18 28 PM" src="https://github.com/GlareDB/glaredb/assets/4040560/f177c60c-c7c3-470f-ad1f-df412330c231">

I changed this:
```python
%%time
import glaredb
import os
cwd= os.getcwd()
con = glaredb.connect()
for tbl in ['nation','region','customer','supplier','lineitem','orders','partsupp','part'] :
 con.sql(f'''CREATE or replace View  {tbl} AS SELECT * FROM parquet_scan('{cwd}/{sf}/{tbl}/*.parquet') ''')
glaredb=execute_query(con, sql)
glaredb.to_csv ('./result/glaredb.csv', index = None, header=True)
```

to this:

```python
%%time
import glaredb
import os
cwd= os.getcwd()
con = glaredb.connect()
for tbl in ['nation','region','customer','supplier','lineitem','orders','partsupp','part'] :
 con.execute(f'''CREATE or replace View  {tbl} AS SELECT * FROM parquet_scan('{cwd}/{sf}/{tbl}/*.parquet') ''')
glaredb=execute_query(con, sql)
glaredb.to_csv ('./result/glaredb.csv', index = None, header=True)
```

`con.sql` to `con.execute`.

`sql` generates the logical plan and doesn't do anything without a call to `show`, `to_pandas`, etc.

`execute` runs the query to completion.

Leaving this open until we've fleshed out our python docs more.

**Comment by djouallah** [comment]
here, we go, please add support for con.sql 

thanks :)
