### ISSUE TITLE
`show` not working in google collab

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#1470]
no, it does not work in colab

_Originally posted by @djouallah in https://github.com/GlareDB/glaredb/issues/1397#issuecomment-1663230075_
            
Strangely enough works in a local terminal:
```
~/Code/github.com/glaredb/glaredb/py-glaredb % ./.venv/bin/python3 examples/show.py 
┌───────┬───────────┬───────┬───────────┐
│ A     │ fruits    │ B     │ cars      │
│ ──    │ ──        │ ──    │ ──        │
│ Int64 │ LargeUtf8 │ Int64 │ LargeUtf8 │
╞═══════╪═══════════╪═══════╪═══════════╡
│ 1     │ banana    │ 5     │ beetle    │
│ 2     │ banana    │ 4     │ audi      │
│ 5     │ banana    │ 1     │ beetle    │
└───────┴───────────┴───────┴───────────┘
┌───────┬────────┬───────┬────────┐
│ A     │ fruits │ B     │ cars   │
│ ──    │ ──     │ ──    │ ──     │
│ Int64 │ Utf8   │ Int64 │ Utf8   │
╞═══════╪════════╪═══════╪════════╡
│ 1     │ banana │ 5     │ beetle │
│ 2     │ banana │ 4     │ audi   │
│ 5     │ banana │ 1     │ beetle │
└───────┴────────┴───────┴────────┘
```

Probably some weird tty detection happening.

**Comment by vrongmeal** [comment]
Can we try and include `to_string()` method and `print` using python?

OR/AND

instead of calling `println!`, we just call python's `print` in show.

**Comment by universalmind303** [comment]
i believe notebooks use `__repr__` under the hood.  so i think we need to add that method to `PyExecutionResult` similar to how we have it in `PyLogicalPlan`

**Comment by djouallah** [comment]
Thank you, it is perfect !!! working as expected
