### ISSUE TITLE
Return number of rows deleted

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#1474]
When running a delete command, the result should include the number of rows deleted so that we can surface that to the user.

              (future): We'll want to also return how many rows were deleted so that we can show that to the user.

_Originally posted by @scsmithr in https://github.com/GlareDB/glaredb/pull/1465#discussion_r1283342703_

**Comment by greyscaled** [comment]
My apologies, I just didn't see which PR closed it. Sorry for noise.
