### ISSUE TITLE
Implement `generate_series` for `Decimal128` instead of floats

### ISSUE THREAD

**Issue by greyscaled** [GlareDB/glaredb#1477]
## Context

```sql
select * from generate_series(0.0, 1.0, 0.1);
```

## Expected

0.0
0.1
0.2
0.3
0.4
0.5
0.6
0.7
0.8
0.9
1.0

## Actual
┌─────────────────────┐
│ generate_series     │
│ ──                  │
│ Float64             │
╞═════════════════════╡
│ 0.0                 │
│ 0.1                 │
│ 0.2                 │
│ 0.30000000000000004 │
│ 0.4                 │
│ 0.5                 │
│ 0.6                 │
│ 0.7                 │
│ 0.7999999999999999  │
│ 0.8999999999999999  │
│ 0.9999999999999999  │
└─────────────────────┘

**Comment by greyscaled** [comment]
Added `needs docs` because I held off on documenting an example since the support isn't quite there yet.

**Comment by greyscaled** [comment]
Gonna also add a `test` label to ensure we have coverage for my example

**Comment by vrongmeal** [comment]
Yeah, this is expected since we're dealing with floating-point numbers. We need another implementation with `Decimal128` (which should be used by default instead of floats). I'll create an issue for this.

**Comment by greyscaled** [comment]
> EDIT: Or we can use this issue for tracking. I'll update the title.

Appreciated!

**Comment by vrongmeal** [comment]
Needs some improvements but almost there...

```
> select * from generate_series(0.0, 1.0, 0.1);
┌───────────────────┐
│ generate_series   │
│ ──                │
│ Decimal128(38, 6) │
╞═══════════════════╡
│ 0.000000          │
│ 0.100000          │
│ 0.200000          │
│ 0.300000          │
│ 0.400000          │
│ 0.500000          │
│ 0.600000          │
│ 0.700000          │
│ 0.800000          │
│ 0.900000          │
│ 1.000000          │
└───────────────────┘
```
