### ISSUE TITLE
cli: INSERT INTO lacks highlighting

### ISSUE THREAD

**Issue by greyscaled** [GlareDB/glaredb#1478]
## Description

![insert-no-highlight](https://github.com/GlareDB/glaredb/assets/11184711/813a3644-64a1-4080-a906-37587c3babdb)

**Comment by universalmind303** [comment]
right now all of the keywords are defined in the [highlighter](https://github.com/GlareDB/glaredb/blob/7f7c1166f62d11b155fd6a08707ac4080f9934ea/crates/glaredb/src/highlighter.rs). Should be pretty easy to add those. (`INSERT,` and `INTO`)
