### ISSUE TITLE
cannot send stream over the buffered channel [programming error]

### ISSUE THREAD

**Issue by greyscaled** [GlareDB/glaredb#1493]
## Description

```json
"jsonPayload": {
    "target": "datasources::bigquery",
    "threadId": "ThreadId(2)",
    "filename": "crates/datasources/src/bigquery/mod.rs",
    "timestamp": "2023-08-04T20:43:45.916355Z",
    "line_number": 316,
    "level": "ERROR",
    "threadName": "server-thread-0",
    "message": "cannot send stream over the buffered channel [programming error]"
}
```

**Comment by scsmithr** [comment]
Was this the result of a query that was running?

**Comment by greyscaled** [comment]
I don't know, saw the qa alert and created the ticket. Not able to check logs atm. Wasn't running any queries or even using qa at the time it occurred.

**Comment by scsmithr** [comment]
Is this still an issue?

**Comment by greyscaled** [comment]
> Is this still an issue?

I have not seen it since, will wait for @vrongmeal's input

**Comment by vrongmeal** [comment]
We can re-open this if required. I think I got a little far with this but still couldn't figure it out. Since we've not seen this for a long time, we can close it for now.
