### ISSUE TITLE
Connect to Cloud deployment from glaredb local or python

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#1505]
## Description

With rpcsrv. The relevant open stuff will use a url in the form of `https://user:pass@hello.remote.qa.glaredb.com:6443/hello`

E.g. local:

```
> \open https://user:pass@hello.remote.qa.glaredb.com:6443/hello
Connected to GlareDB Cloud deployment: "hello"
> 
```

python:

```python
import glaredb
con = glaredb.connect("https://user:pass@hello.remote.qa.glaredb.com:6443/hello")
```

We can come up with prettier schemes in the future.

**Comment by universalmind303** [comment]
`glaredb://user:pass@hello.remote.qa.glaredb.com:6443/hello` ?

**Comment by universalmind303** [comment]
@scsmithr is this done?
It looks like there was some work done in https://github.com/GlareDB/glaredb/pull/1518

**Comment by scsmithr** [comment]
There's still this: https://github.com/GlareDB/glaredb/issues/1525
