### ISSUE TITLE
support mongo predicate pushdowns.

### ISSUE THREAD

**Issue by universalmind303** [GlareDB/glaredb#1507]
## Description

currently all filtering on mongo datasources is done in memory. This can have a pretty significant performance impact on high cardinality predicates. Instead, we should push the filter down to mongo. 

### Details
Should be able to create a function that maps `Expr` to a mongo Bson expression. IDK if all filters will be able to be pushed down, but we should be able to push down most operations.

**Comment by universalmind303** [comment]
duplicates https://github.com/GlareDB/glaredb/issues/730

**Comment by tychoish** [comment]
#2003 does a very course version of this, and means that everything is no longer a table scan. More complex predicates and any kind of transformation (which could be pushed down too,) are out of bounds, for this work.

Long term, if we could translate substrait plans to mongodb grammar, we could probably do more (and this could give us a lot of push-down leverage) but I think the current form is much improved and we can move toward something else later.
