### ISSUE TITLE
Consider making drop execution result singular

### ISSUE THREAD

**Issue by greyscaled** [GlareDB/glaredb#1513]
Would go for tables, views, schemas

## `psql`

```console
postgres=# create table a (a text);
CREATE TABLE
postgres=# create table b (b text);
CREATE TABLE
postgres=# drop table a, b;
DROP TABLE
postgres=# \d
Did not find any relations.
```

## `glaredb local`

```console
> create table t1 (a int );
create table
> drop table t1;
drop tables
```

Seems like it's here: 

https://github.com/GlareDB/glaredb/blob/6017d44073e1d1418c981c3b9ba2913a22e3a1ef/crates/sqlexec/src/session.rs#L171-L173

**Comment by scsmithr** [comment]
I generally agree with this. The commands tags for postgres are singular:

```
test=> create table t1 (a int);
CREATE TABLE
test=> create table t2 (a int);
CREATE TABLE
test=> drop table t1, t2;
DROP TABLE
```

We could probably even go a step further and return number of tables dropped.

**Comment by scsmithr** [comment]
This is done, now says `Table(s) dropped`.

We could get count back, unsure if it's worth the effort right now.
