### ISSUE TITLE
Configure tls for rpcsrv proxy

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#1519]
## Description

Should be straightforward, tonic has support for using rustls.

**Comment by greyscaled** [comment]
Probably `next`. We'll want to have LE/authority certs

**Comment by adhish20** [comment]
using self-signed certificates, throw the below error

Error: tonic::transport::Error(Transport, hyper::Error(Connect, Custom { kind: InvalidData, error: InvalidCertificate(UnknownIssuer) }))

I am checking if there is a workaround for that using openssl
