### ISSUE TITLE
 further refine table display

### ISSUE THREAD

**Issue by universalmind303** [GlareDB/glaredb#1549]
## Description

the cli display is still quite difficult to grok when viewing large tables. 

it seems like just a huge wall of text that is quite hard to decipher.

<img width="1435" alt="image" src="https://github.com/GlareDB/glaredb/assets/21327470/87431b14-a1f6-4b29-873e-6442f18b3892">

for comparison, the same table displayed via polars cli on the same terminal is much more compact & easy to grok. 
![image](https://github.com/GlareDB/glaredb/assets/21327470/e84cc776-9052-43f8-a96b-a8b8a429e6d0)

while the polars one doesn't automatically use the entire width, i still feel like the compact table is much easier to read than the full width one.

**Comment by scsmithr** [comment]
I think the main thing for me is wrapping of some of the values. It can be tricky to see what's wrapped vs what's a separate row.

**Comment by universalmind303** [comment]
💯  I think we should generally truncate instead of wrap.

**Comment by greyscaled** [comment]
@scsmithr did #1738 fix this?

**Comment by scsmithr** [comment]
Yep.

We can follow up with more specific issues as needed.

Something that might make it even better is default to a min-width of 10 (or so) characters for strings. Right now they can get pretty squished depending on the column name.
