### ISSUE TITLE
Chore: Add `physical_plan` module to protogen

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#1580]
## Description

Similar to what we have with `logical_plan`.

I want to be able to encode/decode our custom plans.

**Comment by universalmind303** [comment]
we may need to manually create our own definitions like we did in `logical_plan` as many of these execs will have dependencies on datafusion's structs.

**Comment by scsmithr** [comment]
> we may need to manually create our own definitions like we did in `logical_plan` as many of these execs will have dependencies on datafusion's structs.

I'm good with that. I actually think I prefer using the prost macros over the protobufs...
