### ISSUE TITLE
Copy To physical plan

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#1600]
## Description

This one likely to be tricky.

**Comment by greyscaled** [comment]
We'll do this one after #1599

**Comment by universalmind303** [comment]
here's a checklist of all of the possible paths for copy to. 



- [x] copy local to local - https://github.com/GlareDB/glaredb/pull/1633
- [x] copy local to external (s3,gcs,...) - https://github.com/GlareDB/glaredb/pull/1633
- [ ] copy local to remote
- [ ] copy remote to local
- [ ] copy remote to remote
- [ ] copy remote to external
- [ ] copy external to external


To keep the conditional logic simpler inside the exec, what are your thoughts @scsmithr  @vrongmeal on having individual execs for each of these paths? `CopyLocalToLocalExec, CopyLocalToRemoteExec, ...`. 

I think it'd make the flow a bit easier to follow.

**Comment by vrongmeal** [comment]
except for copy remote to local, all other cases should work 🤔

**Comment by vrongmeal** [comment]
As far as copy execs are concerned, we basically need something to wrap our final physical plan inside something custom (conditionally). Not sure if having different execs helps there, but the part we need to figure out is wrapping the `SendRecvJoinExec` inside a `CopyToLocalExec`.
