### ISSUE TITLE
`SELECT 1` should be executed locally when connected to remote instance

### ISSUE THREAD

**Issue by universalmind303** [GlareDB/glaredb#1616]
## Description
currently if you select from an expression such as `SELECT 1` it executes on the server.  Any queries run on expressions such as this should not be broadcast & instead ran locally.

**Comment by scsmithr** [comment]
👍 My initial thoughts here are we'll have a physical optimizer that will pull the client send/recv stuff up as far as possible. If it ends up being at the top-level, then we just execute everything locally.

**Comment by greyscaled** [comment]
I'm going to add this to `next` for now. We can circle back and re-evaluate that after 0.5.0.
