### ISSUE TITLE
Chore: use ExecutionResult message when executing DDL's

### ISSUE THREAD

**Issue by universalmind303** [GlareDB/glaredb#1641]
## Description
Previous to the RPC implementation of our ddl's, they returned a nice message

```sql
> create table x as (select 1);
create_table
```

now they return an empty table for most of them

```sql
> create table x as (select 1);
[ ]
```

**Comment by scsmithr** [comment]
We'll want to look at doing https://github.com/GlareDB/glaredb/issues/1637 first. Then we can apply that to the cli as well.

**Comment by scsmithr** [comment]
I addressed this in https://github.com/GlareDB/glaredb/pull/1646.

Execution plans now return schemas/batches that indicate what operation they executed, and optionally a count of rows affected. Now execution streams can be inspected to pull out the needed information to recreate the execution result (https://github.com/GlareDB/glaredb/pull/1646/files#diff-aad8c06f1ca0b056364e3f3fed558f918dafdd158bdb1d838d4614c1486c1416R63-R98).

```
> create table hello (a int);
Table created
> insert into hello values (1), (2);
Inserted 2 rows
> insert into hello values (3);
Inserted 1 row
> select * from hello;
┌───────┐
│ a     │
│ ──    │
│ Int32 │
╞═══════╡
│ 1     │
│ 2     │
│ 3     │
└───────┘
```

Let me know your thoughts on the implementation.

**Comment by scsmithr** [comment]
Going to close, assuming this works for everyone.
