### ISSUE TITLE
RPC: invalid EXPLAIN command

### ISSUE THREAD

**Issue by universalmind303** [GlareDB/glaredb#1642]
## Description
error when running following command on a remote server. 
```
> explain select * from parquet_scan('./testdata/parquet/userdata1.parquet') limit 5;
Error: Error during planning: Invalid EXPLAIN command. Expression is empty
```

**Comment by universalmind303** [comment]
Additional context: seems to be directly related to the `LocalSideTableRewriter`. Disabling the rewriter gets rid of this error. It seems that the rewriter is failing on `explain` nodes 🤷.  Will have to further investigate.

**Comment by scsmithr** [comment]
That's actually a bit weird. Not sure why that would fail in the rewrite.

Additionally our explains are (or would be when they work) is opaque to anything past the the client recv/send point:

```
SendRecvExec
  RemoteExecutionExec: deployment=unknown
    CoalescePartitionsExec
      GlobalLimitExec: skip=0, fetch=5
        ClientExchangeRecvExec: broadcast_id=1c579458-2eab-4a4c-9584-e14853fe8904
```
