### ISSUE TITLE
RPC: Unable to insert into temp table

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#1676]
## Description

Working through some slts.

```
> \open http://localhost:6542
Connected to Cloud deployment: unknown
> CREATE TEMP TABLE t1 (a INTEGER, b INTEGER, c INTEGER);
Table created
> INSERT INTO t1 VALUES (1,2,3);
Error: Error during planning: Unable to fetch table provider for 't1': failed to resolve: failed to find table: t1
```

**Comment by vrongmeal** [comment]
I suggest (barring local optimizations) that we do something like the rewrite for `CopyTo`.

If `INSERT INTO` is for a temporary table, send the query to remote for execution, get the result and `InsertExec` into the temporary table locally.
