### ISSUE TITLE
Question: is glaredb a hard fork of datafusion ?

### ISSUE THREAD

**Issue by djouallah** [GlareDB/glaredb#1736]
just a question as I did not know where to ask, is glaredb a hard fork or do you guys keep compatibility with datafusion source code ?

**Comment by scsmithr** [comment]
No, glaredb is not a fork of datafusion, we use it as library. Datafusion provides a lot of great buildings blocks for building a complete database system, and every release includes a lot of improvements. We're currently on datafusion 30 (https://github.com/GlareDB/glaredb/blob/main/Cargo.toml#L14) and try to keep as up to date as possible.

There's some changes that we've made to some parts of datafusion to support things like table functions and hybrid exec. Much of our modifications to datafusion code lives in [datafusion-ext](https://github.com/GlareDB/glaredb/tree/main/crates/datafusion_ext) and in [sqlexec](https://github.com/GlareDB/glaredb/tree/main/crates/sqlexec/src/planner).

We're planning to continue to use as much of upstream datafusion as possible, while making changes where necessary to support features specific to glaredb.

**Comment by djouallah** [comment]
thanks, that make perfect sense
