### ISSUE TITLE
I can't install glardb in Fabric Notebook

### ISSUE THREAD

**Issue by djouallah** [GlareDB/glaredb#1737]
trying to install glaredb in Microsoft fabric notebook, i get this

![image](https://github.com/GlareDB/glaredb/assets/12554469/11762484-3c41-4e82-a9e8-ceac034d3189)

**Comment by scsmithr** [comment]
I'll check this out. We haven't tested with fabric, but I imagine this should be pretty straightforward to get working.

**Comment by scsmithr** [comment]
I have a fix in https://github.com/GlareDB/glaredb/pull/1739. Manually tested to make sure it works in fabric.

Should be ready to go for our next release (this monday).
