### ISSUE TITLE
RPC: AnalyzeExec not serialized

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#1752]
## Description

> Execution error: failed to execute physical plan on remote service: Internal error: Unsupported plan and extension codec failed with [This feature is not implemented: encoding not implemented for physical plan: AnalyzeExec verbose=false

For `explain analyze ...` queries

**Comment by adhish20** [comment]
https://github.com/apache/arrow-datafusion/pull/7574

**Comment by tychoish** [comment]
Given that https://github.com/apache/arrow-datafusion/pull/7574 merged, we can close this once there's a release that we've upgraded to or we should just re-pin to main?
