### ISSUE TITLE
Perf: use range requests when possible for parquet files

### ISSUE THREAD

**Issue by universalmind303** [GlareDB/glaredb#1776]
We can use range requests to optimize our queries on remote datasets. 

## Metadata only count
```sql
select count(*) from 'https://datasets.clickhouse.com/hits_compatible/hits.parquet';
```

We can fulfill this entire query using only the metadata, but instead we try to pull the entire 13GB file into memory, then perform the count. 

## column selection 
```sql
select station_id, name from 'https://localhost/bikeshare_stations.parquet
```
Given the metadata from the footer, we can issue a request for just `station_id` and `name` columns without having to pull in the entire dataset into memory. drastically cutting 

## limit 
```sql
select * from 'https://localhost/bikeshare_stations.parquet limit 1
```
the `RowGroups` in the metadata contain a field `num_rows`. Given the `num_rows` field, we can safely determine how many row_groups we need to pull in. 

## parallelize over the row groups.
instead of fetching everything in a single request, we could fetch the metadata & issue N requests based on N row_groups. This results in more network requests, but should be faster as it'd be less IO constrained. 

I think we'd probably want some kind of threshold on here though, like if the file is < `SOME_THRESHOLD` we don't parallelize, but anything > `SOME_THRESHOLD`, we use parallelization.

**Comment by universalmind303** [comment]
Thinking more about this more.. and I keep coming back to wanting/needing a custom physical planner. I think we _could_ do this with a rewriter rule or physical optimizer rule but it just seems inefficient because we can create that physical node pretty easily when converting the logical plan. 

@scsmithr  @gruuya @vrongmeal any thoughts?

**Comment by vrongmeal** [comment]
(conversation on slack):

cory:
> so for the metadata only count, i'd imagine instead of rewriting an existing physical plan, we could check the logical plan during physical planning. If it meets this "fast path" criteria
> ```
> LogicalPlan::Aggregate{scan: LogicalPlan::Scan(parquet_object_store)), expr: AggregateExpr(Count(1))) => do fast path
> LogicalPlan::Aggregate(other) => not fast path
> ```
> so pretty much my idea is that the fast path criteria can easily be determined up front without having to retroactively apply it. (also avoiding a bunch of dyn casting by checking the physical plan nodes)
> i think the use of a custom planner would also make the DDLRewriter obsolete as we could do that all in a single pass too.


Vaibhav:
> hmm yeah that makes sense, just wondering if there’s any downsides of maintaining our own physical planner. it would be a lot to maintain, given we have rewriter already which can do a lot for us

cory:
> yeah that's kinda where i was at.. It gives us the most flexibility & allows us to do things in a single pass, but also creates more of a maintenance burden.

Vaibhav:
> if there’s isn’t a performance hit, i’d say let’s stick with rewriter for now, but that’s just my opinion

**Comment by universalmind303** [comment]
for the metadata only count, it appears that datafusion already is doing this. See https://github.com/GlareDB/glaredb/issues/1787.  (at least for local files). Fixing this issue may give us metadata only count for free.

**Comment by universalmind303** [comment]
Actually this is WAAY easier than originally thought. Object-store already handles most of these optimizations, we just need to pass in the statistics. Will have a PR soon.
