### ISSUE TITLE
Question, does glaredb support external table using delta table format ?

### ISSUE THREAD

**Issue by djouallah** [GlareDB/glaredb#1780]
is this planned to be supported ?

`con.execute(f'''CREATE or replace external table xxx AS SELECT * FROM delta_scan('/lakehouse/default/Tables/xxxx') ''')`

currently only views a support, just to be very clear, I expect external table to support extra statistics :)

**Comment by gruuya** [comment]
@djouallah I'm happy to say that as of the next glaredb release (0.5.1) you'll be able to create both external Delta and Iceberg tables in an arbitrary object store. 

You can do this using the regular [`CREATE EXTERNAL TABLE`](https://docs.glaredb.com/glaredb/sql-commands/create-external-table/) command, with `data-source-type` set to `delta`/`iceberg` as appropriate, and providing the relevant connection options for the object store in question. Let me know if you find any issues with this functionality.

**Comment by greyscaled** [comment]
I'm reopening this, and will close it once `0.5.1` is released.

**Comment by greyscaled** [comment]
Hey all (cc @djouallah) [0.5.1](https://github.com/GlareDB/glaredb/releases/tag/v0.5.1) is out :tada:

**Comment by djouallah** [comment]
Thank you
