### ISSUE TITLE
Include precompiled binaries in the release

### ISSUE THREAD

**Issue by universalmind303** [GlareDB/glaredb#1802]
## Description

It'd be nice for end users to be able to simply download the precompiled binary for their arch.

**Comment by scsmithr** [comment]
We already include common ones:
<img width="360" alt="Screenshot 2023-09-22 at 12 12 50 PM" src="https://github.com/GlareDB/glaredb/assets/4040560/20b55d6e-54c2-45e4-8a3d-7c1686a65a61">

And `curl https://glaredb.com/install.sh | sh` actually pulls from these releases.

Is this issue about adding more?

**Comment by universalmind303** [comment]
idk how i missed that.
