### ISSUE TITLE
Allow using GCS and S3 for underlying data storage when running locally

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#1806]
## Description

Currently we have the `--data-dir` flag which allows specifying a local path. We can extend this (or add another flag) to allow providing an object store bucket instead. This would act similarly to the existing `data-dir` behavior in that both the catalog and table data will be stored in the same place.

We also do some parsing the python lib to detect cloud vs. local. We can extend that to also detect s3/gs: https://github.com/glaredb/glaredb/blob/fb8d15c7d86c32d368503a42b27d3f95cc897410/py-glaredb/src/lib.rs#L60-L80

I'm not sure how we want to provide credentials here yet. Ideally we could look at the configured credentials in the user's home, but I'd want a way to manually specify the creds to. For python, we could use kwargs to independently specify access key, region, etc.

**Comment by gruuya** [comment]
I assume that, since we're focusing on localy run GlareDB, it's ok to use the in-process metastore client in this case?
https://github.com/GlareDB/glaredb/blob/d95ae28f6b53f10dd5072a12e6cff7b4bb96f730/crates/metastore/src/local.rs#L28-L34

**Comment by scsmithr** [comment]
Yep, in process is the way to go.

We can probably update the comment to remove 'This should never be used in production.'.

**Comment by jordandakota** [comment]
Any reason why azure containers wouldn't be added to the list of s3 and gcs buckets?

**Comment by scsmithr** [comment]
> Any reason why azure containers wouldn't be added to the list of s3 and gcs buckets?

Azure is definitely something we want to support near-term. We're just more familiar (and have testing infra) for S3 and GCS. But adding in Azure should be straightforward and we can work on that once we're able to test this with GCS/S3.
