### ISSUE TITLE
Chore: Action for running benchmarks

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#1822]
## Description

The idea is to add it as a github runner, then have `runs-on: ubuntu-benchmarks-8-core` for a benchmark step in github actions.

This would give us relatively consistent results across runs. To reduce contention on this vm, we should probably only have benchmarks run on merges to main (and workflow_dispatch).

**Comment by greyscaled** [comment]
I can help out with this one if that's useful?

**Comment by scsmithr** [comment]
> I can help out with this one if that's useful?

sgtm. We can just add a separate workflow with just a quick `echo hello` or something to test that it works until Cory finishes up his pr.

I think the we could do a 8 core, 16G mem vm with like 100G disk for now.

**Comment by universalmind303** [comment]
would we really want to run the benches on every single pr/commit? I always assumed that they would be more ad-hoc.

**Comment by greyscaled** [comment]
> we should probably only have benchmarks run on merges to main (and workflow_dispatch)

> would we really want to run the benches on every single pr/commit?

Discussed on Slack:

- We'll want to run the big benchmarks^TM on:
  - some controlled cadence like nightly or similar (other examples given were every 10K lines or every 10 merges)
  - when vendors release
- In addition might want to have a micro-benchmark we can run on each commit

**Comment by greyscaled** [comment]
We're going to start out with just a dedicated gh runner

**Comment by vrongmeal** [comment]
Adding a new runner is quite simple. I set up my local machine as a runner (to test it out) on a private repo.

@greyscaled, we can hop on Discord today and quickly set this up. We don't need to automate anything here. But having a ready-to-go image that we can spin up would be nice.

One thing that might bother us is cleaning up the VM after each job. This can be mitigated by making benchmarks use a `TMP` directory and cleaning up afterwards. We could also cleanup/re-initialize the runner every weekend or so. But that's a problem for later, I suppose.

**Comment by greyscaled** [comment]
Discussed in Slack:

> Let's go ahead to write the yaml for the benchmarks with just ubuntu runners, then once it's working, we can just go ahead and bump to the existing ubuntu-latest-8-cores runners.
