### ISSUE TITLE
Turn tls on by default

### ISSUE THREAD

**Issue by greyscaled** [GlareDB/glaredb#1828]
When the feature is ready to be GA'd, remove these:

- rpc srv: https://github.com/GlareDB/glaredb/blob/d95ae28f6b53f10dd5072a12e6cff7b4bb96f730/crates/glaredb/src/args/mod.rs#L58
- local: https://github.com/GlareDB/glaredb/blob/d95ae28f6b53f10dd5072a12e6cff7b4bb96f730/crates/glaredb/src/args/local.rs#L66

**Comment by greyscaled** [comment]
Putting `on-hold` simply because we shouldn't flip this switch until ready.

**Comment by tychoish** [comment]
Next steps: 
- let's put a warning in the next release notes (if it's a point release)
- if its easy to add warning in error message when/if it breaks?
- can we add a warning message pre-breaking that says "it's about to break in the next release?" (does that make sense)?

(when pre-work/warning/docs are done move this ticket to next milestone) 

@tychoish to look and see if there's a way to do fallback on one port?

**Comment by greyscaled** [comment]
> @tychoish to look and see if there's a way to do fallback on one port?

**tonic**: https://docs.rs/tonic/latest/tonic/transport/index.html

https://github.com/GlareDB/glaredb/blob/5194a79be917e6e1ca9898ae07b31ae0198122ed/crates/glaredb/src/rpc_proxy.rs#L45-L57

**Comment by tychoish** [comment]
My inclination/memory, was that we could add https://docs.rs/tonic/0.9.2/tonic/transport/server/struct.ServerTlsConfig.html#method.client_auth_optional option to the server tls-config, and then turn clients on to sending config (and do that now/in the next release, with the warning message changes) and then in the following release fix things. 

It's not so much that I think it's a problem to break things at this point, but more, that I think if we can get a hang of doing a tick/tock release pattern for client server stuff now, it'll pay off later..
