### ISSUE TITLE
Does glaredb have plans to support fully distributed execution?

### ISSUE THREAD

**Issue by liurenjie1024** [GlareDB/glaredb#1861]
It's interesting to know your plans for distributed execution like arrow-ballista

**Comment by scsmithr** [comment]
We do have plans to support distributed execution, but we're still in the planning phases of that.

As a side note, we do have a form of distributed execution by way of hybrid execution: https://docs.glaredb.com/glaredb/hybrid-execution/. The aim here being able to pool the resources of your Cloud deployment and laptop when executing queries.

**Comment by liurenjie1024** [comment]
> We do have plans to support distributed execution, but we're still in the planning phases of that.
> 
> 
> 
> As a side note, we do have a form of distributed execution by way of hybrid execution: https://docs.glaredb.com/glaredb/hybrid-execution/. The aim here being able to pool the resources of your Cloud deployment and laptop when executing queries.

Cool, looking forward to see the design and roadmap.

**Comment by tychoish** [comment]
We're tracking the work associated with this epic in #1867, and I think the answer is very firmly "yes". 

I'm going to go ahead and close this, but feel free to reach out with more questions in the future.
