### ISSUE TITLE
Track additional metrics at the data source level

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#1862]
## Description

Related: https://github.com/GlareDB/glaredb/pull/1860

- Bytes written
  - Inserts, updates (maybe)
  - Create table as

(And probably more as we discover them)

Bytes written should track the bytes of the final record batch immediately prior to persisting. This should not attempt to track the size of the resulting objects (as it wouldn't be compatible with possibly writing to data sources).

**Comment by greyscaled** [comment]
I'm not sure if this is still an issue and/or how it relates to #1929

**Comment by scsmithr** [comment]
Superseded by more specific issues.
