### ISSUE TITLE
Chore: Implement end-to-end testing aside from SLTs

### ISSUE THREAD

**Issue by gruuya** [GlareDB/glaredb#1878]
## Description

More specifically, implement them as regular (async or not) Rust tests. This would probably involve spinning up a local/server GlareDB instance as a fixture of sorts, and then having the tests share that.

The motivation here is that, while SLTs are in principle great, they are somewhat opaque in the sense that asserting side effects is very hard. Take for instance a `VACUUM` statement: validating that it performed what is expected can't really be done effectively via SLTs, whereas if one had access to the underlying object store one could do it in an explicit manner. Same goes for interleaving of sensitive query combinations.

Some ideas here: https://github.com/splitgraph/seafowl/blob/main/tests/statements/vacuum.rs

**Comment by scsmithr** [comment]
@vrongmeal has had similar ideas previously.

**Comment by tychoish** [comment]
The pytest harness I cooked up last week does this. (#2258)
