### ISSUE TITLE
Add the storage background jobs back again

### ISSUE THREAD

**Issue by vrongmeal** [GlareDB/glaredb#1885]
## Description

Add the bg jobs back again that were removed when working on hybrid exec (RPC) stuff.

For example: https://github.com/GlareDB/glaredb/blob/7b4937a1c067e68863d2a2787ed05ccdf4c28f30/crates/sqlexec/src/planner/physical_plan/insert.rs#L118

**Comment by greyscaled** [comment]
I'm not entirely sure we need to do this (at all). We should discuss further offline.

**Comment by tychoish** [comment]
I think this is "gone away" for various reasons. The commit did the appropriate cleanup, and we're addressing this accounting using other means.
