### ISSUE TITLE
Chore: Remove dtolnay/rust-toolchain?

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#1940]
## Description

And just use the version in the actions image? Seems like it's being updated pretty frequently.

Rust tools in the image can be found here: https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#rust-tools

**Comment by tychoish** [comment]
a few things:
- the patch of a few days adds in an explicit toolchain fetch in a lot of steps that don't need them (e.g. because they already have them via the cache)
- I'm inclined to _not_ to do this because:
  - if we rely on the version on the image, it can change without our intervention causing PRs to start failing.
  - old tasks, particularly, say benchmarks (if we skip some) because commits are pushed in groups, that we decide to run _after_ could break, or have in consistent results if run with the unexpected version of a toolchain. same with rerunning old tests.

**Comment by scsmithr** [comment]
> the patch of a few days adds in an explicit toolchain fetch in a lot of steps that don't need them (e.g. because they already have them via the cache)

I'd argue that we should just stick it in every step since it's sometimes tricky to know if we have everything in the cache. The "Build" step only compiles things using the "dev" profile. Things like tests use a separate "test" profile, and so there's some additional compilation that needs to be done (which won't be in the cache).

The pr I put in over the weekend was a result of CI failing on the clippy step since the runner image updated from rust 1.72 to 1.73 and there were a few lints added this release.

**Comment by universalmind303** [comment]
wondering if we can just add a [rust-toolchain.toml](https://github.com/GlareDB/glaredb/pull/1947)? 
will that be respected by the ci?

**Comment by tychoish** [comment]
> I'd argue that we should just stick it in every step since it's sometimes tricky to know if we have everything in the cache. The "Build" step only compiles things using the "dev" profile. Things like tests use a separate "test" profile, and so there's some additional compilation that needs to be done (which won't be in the cache).

As configured, I believe that the toolchain is supposed to be in the cache, and we should never install the tool chain without clippy/etc. (and maybe make sure the `justfile` checks the path for the actions-installed rust, if we want to keep this path) 

> will that be respected by the ci?

Do you have to run `rustup` to setup the toolchain in order for this to work? (and if this results in us doing measurable work; we should make sure it's included in the cache.) 

-------

I think my new thought is:

- we commit the change, and remove actions installed rust
- we do this rust-toolchain work as in #1947
- we make sure that the rust-toolchain file is respected by the justfile
- we confirm that `rustup`-installed artifacts are cached.
