### ISSUE TITLE
build(apple): upgrade Node action

### ISSUE THREAD

**Issue by greyscaled** [GlareDB/glaredb#1955]
https://github.com/GlareDB/glaredb/actions/runs/6643526032

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: extractions/setup-just@v1, actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by tychoish** [comment]
I'm not sure where the commit for this went, but v0.6.1. didn't have this problem. Going to go ahead and close this! Feel free to reopen if I missed something.
