### ISSUE TITLE
CLI: How can I clear the screen?

### ISSUE THREAD

**Issue by greyscaled** [GlareDB/glaredb#2023]
In `psql` I can use `\! clear`, where `\!`:

>  \! [COMMAND]           execute command in shell or start interactive shell

**Comment by greyscaled** [comment]
It looks like I just `CTRL+c` a lot to do this, but my screen fills up with `>` prompts then.

**Comment by universalmind303** [comment]
@greyscaled  we use `reedline` for the cli. Reedline uses emacs keybindings by default, so `ctrl + l` should clear the screen.

**Comment by greyscaled** [comment]
Awesome, I'll close out!
