### ISSUE TITLE
Allow reading json arrays

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#2028]
## Description

Currently we only support reading new line delimited json. I'd to also support complete json arrays so that we can read files in the form of:

```
[
  {
    <object1>
  },
  {
    <object2>
  }
]
```

**Comment by universalmind303** [comment]
this should probably happen upstream in either datafusion or arrow-rs.

**Comment by tychoish** [comment]
> this should probably happen upstream in either datafusion or arrow-rs.

Likely, though I think I'm inclined to implement this locally, and then try and upstream it, unless there's an obvious way to do this trivally in the upstream.

Also sorry for opening the duplicate issue. I'm inclined to keep the #2218 issue open.
