### ISSUE TITLE
feat: infer lance file format

### ISSUE THREAD

**Issue by universalmind303** [GlareDB/glaredb#2067]
we should be able to infer lance format like we do with other file types

`select * from './my_table.lance'`

**Comment by tychoish** [comment]
it seems like all of our support is for lance databases (which would be directories rather than files, or were you thinking about something else here?

(And if so how do you create such a file 😂)

**Comment by tychoish** [comment]
I'm inclined to think that for delta/lance/iceberg we shouldn't infer format from the path, because they're not files and that ambiguity leads to more confusion that it helps.

**Comment by universalmind303** [comment]
> I'm inclined to think that for delta/lance/iceberg we shouldn't infer format from the path, because they're not files and that ambiguity leads to more confusion that it helps.

yeah i think inference should be limited to file formats, not table formats.
