### ISSUE TITLE
\open command fails if it doesn't exist

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#2087]
## Description

```
> \open ./test
Error: No such file or directory (os error 2)
```

**Comment by universalmind303** [comment]
I think i introduced this with the tilde support. Will look into it.

**Comment by greyscaled** [comment]
Is there a missing test we can add ?

**Comment by scsmithr** [comment]
Double check that we're writing the `database` folder to the right place. I came across an errant folder that wasn't in the directory I specified, but I haven't reproduced yet (working on the sql server stuff).
