### ISSUE TITLE
Better error message when wrong glaredb command

### ISSUE THREAD

**Issue by vrongmeal** [GlareDB/glaredb#2102]
## Description

Since `glaredb` defaults to `local` command, running a command that doesn't exist (maybe because of a typo) returns a bad error message:

```
❯ ./glaredb version
Error: No such file or directory (os error 2)
```

This is because it's trying to read a file called `version` since there's no subcommand called `version`.

I would expect an error message explaining that the command `version` or an SQL file called `version` (both) do not exist.

**Comment by universalmind303** [comment]
duplicate of #2101
