### ISSUE TITLE
syntax Highlighting doesnt work properly for prql dialect

### ISSUE THREAD

**Issue by universalmind303** [GlareDB/glaredb#2114]
## Description
When the dialect is set to prql, it is still using the sql highlighting. 

<img width="448" alt="image" src="https://github.com/GlareDB/glaredb/assets/21327470/bf5cb338-ab38-4649-8ed2-5d8e83eddec3">

Instead it should use different highlighting logic specific to the prql language.

**Comment by hemanth94** [comment]
@universalmind303  I was trying to fix this.
After going through code, I realised there is no different highlighting logic written in `fn colorize_sql()` . It was written for `GenericDialect`.
Can we just add missing keywords for PRQL like : [sort, take, filter..etc], so they can be highlighted.
Please suggest. Thanks.

**Comment by universalmind303** [comment]
>  Can we just add missing keywords for PRQL like : [sort, take, filter..etc], so they can be highlighted. 

@hemanth94 I think that should be fine for now. Long term, i think we'd want a dedicated `colorize_prql` function that is used when dialect is set to `prql`
