### ISSUE TITLE
chore: rename `CREATE CREDENTIALS` to `CREATE CREDENTIAL`

### ISSUE THREAD

**Issue by universalmind303** [GlareDB/glaredb#2133]
## Description

The `CREATE CREDENTIALS` command in our SQL engine suggests that it is plural in nature (creating multiple credentials). It is instead singular and creates a single credential. other databases tend to use the singular vocabulary like [CREATE SECRET](https://docs.snowflake.com/en/sql-reference/sql/create-secret) or [CREATE CREDENTIAL](https://learn.microsoft.com/en-us/sql/t-sql/statements/create-credential-transact-sql?view=sql-server-ver16).

Thoughts on renaming to one of the aforementioned?

**Comment by universalmind303** [comment]
Should we keep the `CREATE CREDENTIALS`, but put a deprecation message that it'll be removed in a later release?

something like 
```sh
> CREATE CREDENTIALS comment1 PROVIDER debug
::: OPTIONS (table_type = 'never_ending');
Credentials created
  DEPRECATION WARNING. `CREATE CREDENTIALS` is deprecated and will be removed in a future release. Please use `CREATE CREDENTIAL` instead.  
```

**Comment by Lilit0x** [comment]
Hi there, @universalmind303, I am interested in working on this. I have a question though, should the same be done for `DROP CREDENTIALS`?
