### ISSUE TITLE
manpage is not compatible with mandoc(1) and might display incorrectly.

### ISSUE THREAD

**Issue by universalmind303** [GlareDB/glaredb#2135]
## Description
```sh
> man ./glaredb
Ïúíþ????????????????ø???�? ?????????H???__PAGEZERO??????????????????????????????????????????????????????????x???__TEXT???????????????????�®??????????????�®?????????????????????__text??????????__TEXT??????????�???????xù½?????�??????????????????�????????????__stubs?????????__TEXT??????????ø?¾?????à
> q
This manpage is not compatible with mandoc(1) and might display incorrectly.
```

**Comment by scsmithr** [comment]
Should this behave differently? I wouldn't expect to run man on a binary.

**Comment by universalmind303** [comment]
🤦 yeah i'm just dumb. I ran `duckdb` and got `No manual entry for duckdb`, and a few other ones that said either `no entry`, or showed the manpage, but those are all installed through a package manager _(homebrew)_. If i run `man ./duckdb` it gives me the same thing.
