### ISSUE TITLE
Benchmark upload failure: No such file or directory

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#2160]
## Description

```
just benchmarks/tpch upload_log main 6983024191 1
just tpch/upload_log main 6983024191 1
cp: cannot stat 'timings.csv': No such file or directory
Connected to Cloud deployment (TLS enabled): benchmarks
┌──────────┐
│ Int64(1) │
│       ── │
│    Int64 │
╞══════════╡
│        1 │
└──────────┘
Error: External error: External error: No such file or directory (os error 2)

Caused by:
    0: External error: No such file or directory (os error 2)
    1: No such file or directory (os error 2)
error: Recipe `upload_log` failed with exit code 1
error: Recipe `tpch` failed on line 5 with exit code 1
```

**Comment by universalmind303** [comment]
the timings file is only generated if you export `LOG_TIMINGS=true`.

**Comment by vrongmeal** [comment]
I don't think this is an issue anymore? Should we close this?

**Comment by tychoish** [comment]
I think the problem was "if the benchmarks failed and didn't write a file" we tried to upload a file that didn't exist. 

I'm not sure what changed to make this not possible, but if so, then I'm happy to close it.

**Comment by vrongmeal** [comment]
Yeah, that might still be a problem. But I'll take this up when benchmarking dist exec stuff. Let's leave this open and I'll assign it to myself.

**Comment by universalmind303** [comment]
Reassigned to me as I wrote those benchmarks.
