### ISSUE TITLE
external table `location` keyword shouldn't be case sensitive. 

### ISSUE THREAD

**Issue by universalmind303** [GlareDB/glaredb#2199]
## Description

the `location` property in the following is case sensitive. 

```sh
> ./target/release/glaredb local -q "CREATE EXTERNAL TABLE customer FROM LOCAL (LOCATION 'testdata/parquet/userdata1.parquet')"
Error: sql parser error: missing option: location
```

```sh
> ./target/release/glaredb local -q "CREATE EXTERNAL TABLE customer FROM LOCAL (location 'testdata/parquet/userdata1.parquet')"
Table created
```

## Expected behavior

both `location` and `LOCATION` work the same, as well as any other case insensitive variants

I want to write all of my queries in spongebob case

```sql
CrEaTe ExTeRnAl TaBlE supplier fRoM lOcAl (LoCaTiOn 'testdata/parquet/userdata1.parquet')
```

**Comment by seve-martinez** [comment]
Is it sufficient to just force the entire query input to be lowercase? Or are there other implications of doing that?

**Comment by universalmind303** [comment]
> Is it sufficient to just force the entire query input to be lowercase? Or are there other implications of doing that?

I think that's what sqlparser does, so that should be fine.
