### ISSUE TITLE
Chore: Require node bindings test in CI

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#2209]
## Description

Currently not required.

**Comment by tychoish** [comment]
done

**Comment by greyscaled** [comment]
I don't think this one was completed, possibly accidentally closed.

**Comment by greyscaled** [comment]
nvm i misunderstood, this is in fact done

**Comment by scsmithr** [comment]
This was done, the issue we're currently hitting is the release for node bindings, not the tests.

**Comment by greyscaled** [comment]
> is the release for node bindings, not the tests

Hitting npm cache in regular CI runs makes this error trickier to observe. I misunderstood the original issue, I thought that we didn't have a check in regular CI; we do, it just wasn't a required check.
