### ISSUE TITLE
Chore(refactor): move all sqlexec/functions to sqlbuiltins/functions

### ISSUE THREAD

**Issue by universalmind303** [GlareDB/glaredb#2213]
## Description
Currently all of our udfs are defined in `sqlexec/src/functions`, but all of the udtfs and datafusion provided functions are defined in `sqlbuiltins/functions`. We should move all of the functions out of sqlexec and in to `sqlbuiltins`. This'll help make them easier to document & also show up in the catalog. 

Notably, the new `kdl_select` and `kdl_matches` functions are not available in `glare_catalog.functions`. Nor are any of the postgres utility functions such as `pg_table_is_visible`.

**Comment by universalmind303** [comment]
potentially related to https://github.com/GlareDB/glaredb/issues/2013. 

I don't think anything in `sqlexec/functions` is getting registered in the datafusion function registry.

**Comment by seve-martinez** [comment]
I'd be happy to take this. 🚀

**Comment by tychoish** [comment]
@seve-martinez it looks like @universalmind303 is working on it in @2214! Thanks for your interest/attention though!
