### ISSUE TITLE
Simple query stream doesn't EOF properly

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#2242]
## Description

https://github.com/glaredb/glaredb/blob/bd684254b29fcff0e4bcafd8f4deab1ae1a61d59/crates/rpcsrv/src/handler.rs#L378-L416

Causes context deadline exceeded on cloud.

**Comment by universalmind303** [comment]
@scsmithr I wonder if it'd be easier to just use the go flightsql driver for cloud? 


The following works on [this branch](https://github.com/GlareDB/glaredb/pull/2219)
```go
package main

import (
	"database/sql"
	_ "github.com/apache/arrow-adbc/go/adbc/sqldriver/flightsql"
)

func main() {
	db, err := sql.Open("flightsql", "uri=grpc://0.0.0.0:6789")
	if err != nil {
		panic(err)
	}
	defer db.Close()

	if err = db.Ping(); err != nil {
		panic(err)
	}

	rows, err := db.Query("SELECT registration_dttm from './testdata/csv/userdata1.csv' limit 1")
	if err != nil {
		panic(err)
	}
	columns, err := rows.Columns()
	if err != nil {
		panic(err)
	}

	println(columns[0])

}
```

**Comment by scsmithr** [comment]
This fix here is actually super easy.

We can switch to flight sql once it's ready. The code being written in https://github.com/GlareDB/cloud/pull/2527 would still be needed--it would be easy to swap the client out whenever.
