### ISSUE TITLE
CLI tests frequently hits the timeout for me

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#2274]
## Description

(The rust ones)

E.g.

```
---- test_data_dir stdout ----
thread 'test_data_dir' panicked at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/ops/function.rs:250:5:
Unexpected failure.
code=<interrupted>
stderr=```""```
command=`"/Users/sean/Code/github.com/glaredb/glaredb/target/debug/glaredb" "-f" "/var/folders/4l/fnrk81pn6nj924xq52rwxnbc0000gn/T/.tmpkUFDJZ" "-q" "create table test as select 1"`
code=<interrupted>
stdout=""
stderr=""
```

This can happen in any of the tests for me. Sometimes everything passes, sometimes one test fails, sometimes many tests fail.

Increasing `DEFAULT_TIMEOUT` to 5 secs makes the tests consistently pass for me. Why was this lowered?

**Comment by universalmind303** [comment]
I set it lower to speed up the testing suite. happy to bump it back up to 5s. Originally, I wanted to send a `sigkill` to the application, but `assert_cmd` doesn't seem to support that. So the timeout is still a bit of a hack, but it seems the best available without manually spawning the task.

**Comment by scsmithr** [comment]
Is there a test that depends on hitting this timeout? When would we expect the binary to hang?

**Comment by universalmind303** [comment]
> Is there a test that depends on hitting this timeout? When would we expect the binary to hang?

it's when we run the `./glaredb server` commands. those run indefinitely. So we either have to send a signal to kill it, or set a timeout. Since `assert_cmd` doesn't support sending signals, we just set a timeout.

**Comment by scsmithr** [comment]
I don't know what changed, but I don't seem to be hitting this now. Will reopen if I see it again.

I'd like to do proper signal sending to make that all more robust, but timeouts work for us right now.
