### ISSUE TITLE
build and release dependency graph

### ISSUE THREAD

**Issue by greyscaled** [GlareDB/glaredb#2555]
I'm proposing that we only deploy artefacts after _all_ builds succeed and pass a smoke test.

The smoke test would be the last step in the build matrix and must run on the target that was used to build.

```
binaries matrix     |
image               |  -- if all succeed --> Deploy matrix
py matrix           | 
node matrix         |
```

**Comment by tychoish** [comment]
the smoke test is hard because you sort of want to do the smoke test on a different system than the one you compiled or packaged on, otherwise it's easy to leak an implicit dependency on the build environment. 

Even without a smoke test, this flow makes sense though.

**Comment by greyscaled** [comment]
> the smoke test is hard because you sort of want to do the smoke test on a different system than the one you compiled or packaged on, otherwise it's easy to leak an implicit dependency on the build environment.
> 
> Even without a smoke test, this flow makes sense though.

that's fair, and adding a smoke test is sufficiently orthogonal to reworking the dependency graph

**Comment by tychoish** [comment]
smoke testing the release is hard, in part because you don't want to do it on the system that you build the artiifact on, because you can have implicit dependencies on the build environment/system
