### ISSUE TITLE
fetch sqlite databases from object storage

### ISSUE THREAD

**Issue by vrongmeal** [GlareDB/glaredb#2643]
## Description

https://github.com/GlareDB/glaredb/pull/2568#discussion_r1476153648

**Comment by tychoish** [comment]
as I was thinking about this, we might be fine to not have a size limit here: we don't have a size limit for any other kind of file, and say, JSON (non-new-line) and excel would all run into size limits in the same way (parquet and csv and ndjson and bson can all be streamed), so we might as well just download whatever now and solve the limited space issue separately.

**Comment by talagluck** [comment]
Beyond just being able to hit this in object storage from one of the major cloud providers, it would be nice to access this anywhere it's available, e.g. GitHub:
```
CREATE EXTERNAL DATABASE census_names
FROM sqlite
OPTIONS (
location = 'http://2016.padjo.org/files/data/starterpack/census/census2000names.sqlite',
);
```

**Comment by talagluck** [comment]
How would that interact with the `INSERT INTO` feature just added in #2745?

**Comment by tychoish** [comment]
We'd have to prevent inserts in these cases
