### ISSUE TITLE
`CREATE EXTERNAL TABLE` support for excel

### ISSUE THREAD

**Issue by tychoish** [GlareDB/glaredb#2644]
Currently Excel file reading is only available as a table function, but we could support `CREATE EXTERNAL TABLE` from excel files as we do for other formats. 

The code to do this is similar to the code for the other formats and there's nothing that is special about excel files, it's just a matter of hooking it all up and writing a few tests.

**Comment by greyscaled** [comment]
Do I have it correct that we would start with `create external table` which would specify a `sheet`, and that we could later add `create external table` that maps all sheets to tables?

**Comment by hemanth94** [comment]
@tychoish Can i try contributing to this? 
Will ask for suggestions if needed.

Thanks,

**Comment by tychoish** [comment]
@hemanth94 this would be great for you! I cannot imagine that there'll be anything unusual. the `bson` example, which I did recently, is pretty clean and might be a good thing to look at for a model.
