### ISSUE TITLE
Bug: Enable altering views through the ALTER TABLE function

### ISSUE THREAD

**Issue by talagluck** [GlareDB/glaredb#2676]
## Description
I'm hitting an issue with dbt where it works fine for tables but panics when it hits views.

I just did a round of debugging with @scsmithr and it seems like the issue is that it's running an ALTER TABLE function to rename a view. Looking for two things here:
1. ALTER TABLE should work on views for renaming views
2. Don't panic

**Comment by scsmithr** [comment]
Specifically panicking here: https://github.com/glaredb/glaredb/blob/db252ce59d066e073b40be0d30eecc30f61a130e/crates/metastore/src/database.rs#L938-L941

**Comment by greyscaled** [comment]
I can look into this one today after #2670 merges if no one else is picking it up
