### ISSUE TITLE
Should I be able to copy a delta table to lance locally?

### ISSUE THREAD

**Issue by greyscaled** [GlareDB/glaredb#2713]
Following doesn't work for `FORMAT lance`:

```shell
> create table hello (a text);
Table created
> copy (SELECT * from hello) to './output.csv';
Copy success
> copy (SELECT * from hello) to './output.lance';
Error: External error: External error: Failed to canonicalize path "./output.lance": No such file or directory (os error 2)
> copy (SELECT * from hello) to './output.lance' FORMAT lance;
Error: External error: External error: Failed to canonicalize path "./output.lance": No such file or directory (os error 2)
> 
```

**Comment by tychoish** [comment]
ok, so what's happening here is that, it's treating the path you provide as the prefix where the lance files/tables should live, and when the directory doesn't exist, it errors. (opaquely) if I made the directory before I ran the command it worked. (also lance tables have more than one file, so `output.lance` may be misleading.

also observed: when the source table is empty nothing is written. (seems correct.)

**Comment by universalmind303** [comment]
I think the use of the lance destination as a **file** in the first example is a bit misleading & maybe we need some documentation around. We should have some clear boundary between file formats (bson, json, csv, parquet, xlsx) and table formats
 (delta, lance).

**Comment by greyscaled** [comment]
Yep, it stems from not realizing I needed to provide a dir (and not entirely seeing why based on other uses of the command + error message). Distinguishing between table and file formats is a good point.

**Comment by tychoish** [comment]
I think the "table" vs "file format" thing breaks down with hive partitioning and globbing, and doesn't feel like a super useful conceptual framework.

We could create directories for lance output if they don't exist, that wouldn't be very absurd.

**Comment by greyscaled** [comment]
> I think the "table" vs "file format" thing breaks down with hive partitioning and globbing

Also good point!

**Comment by tychoish** [comment]
@greyscaled I agree that this is confusing but I'm not sure what we should do here?

**Comment by greyscaled** [comment]
@tychoish your comment here:

> We could create directories for lance output if they don't exist, that wouldn't be very absurd.

seems sufficient to close this, in addition to documentation on `COPY TO` and formats
