### ISSUE TITLE
ci gets stuck on `pytest`

### ISSUE THREAD

**Issue by universalmind303** [GlareDB/glaredb#2731]
## Description

the tests aren't even running, and just getting stuck before running.

https://github.com/GlareDB/glaredb/actions/runs/8144103255/job/22257825450?pr=2716

**Comment by tychoish** [comment]
This is a reporting error in github actions. 

I canceled the test (which wasn't running, but had failed to report in,) and reran the task and got this error:

https://github.com/GlareDB/glaredb/actions/runs/8144103255/job/22270856182
