### ISSUE TITLE
Bug: `IF NOT EXISTS` not implemented for `CREATE EXTERNAL DATABASE`

### ISSUE THREAD

**Issue by talagluck** [GlareDB/glaredb#2921]

**Comment by greyscaled** [comment]
Note - we're looking to release after this gets patched

**Comment by talagluck** [comment]
Hmm - on second glance, this appears to be working fine. I think I left out the name of the external database earlier, then thought the `if not exists` was what was broken, then figured out the real reason and didn't add that back. Closing for now; I'll add an issue to the docs repo to update the documentation here.
