### ISSUE TITLE
Implement "major" postgres catalog views

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#536]
## Summary

A few additional postgres tables were added in https://github.com/GlareDB/glaredb/pull/534. We'll want to continue to flesh out these tables. Our goal here isn't to implement all postgres tables, nor is to have completely correct semantics. So we'll want to add the "major" postgres tables, even if most of the columns returned back are `null`.

What's considered "major" isn't clear, but I think implementing most of what duckdb implements would be a good start: https://github.com/duckdb/duckdb/blob/master/src/catalog/default/default_views.cpp#L30-L49

### Specifications

- Add the "major" views

## Rationale

Postgres catalog compatibility.

External postgres tooling (some tools might be querying catalog under the hood and not work without the right compat)

**Comment by greyscaled** [comment]
we've been doing this with #2436
