### ISSUE TITLE
Occasional errors hitting metastore

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#596]
## Context

<img width="623" alt="Screenshot 2023-02-04 at 4 19 11 PM" src="https://user-images.githubusercontent.com/4040560/216791853-a741a2aa-a4b6-4667-844f-933fb7cca95f.png">

Probably just from stale connections since retrying works.

## Expected

We don't get errors when connecting to metastore

## Actual

We get errors connecting to metastore (probably when metastore redeploys and a node has a connection for an old one)

## Impact

Cloud ux

**Comment by greyscaled** [comment]
We haven't seen this in a while, going to close.
