### ISSUE TITLE
Improve CSV Type Inference for display and filtering

### ISSUE THREAD

**Issue by vrongmeal** [GlareDB/glaredb#697]
## Context

Arrow reader's type inference is not upto the mark. It works well for `int`, `float`, `string`, and `date` but resolves to text for other types. Moreover, for timestmps, it sees the date and maps it to a date which later errors in a parse error.

## Expected

For all standard datatypes to be inferred properly:
* Integer
* Floating point
* String
* Binary
* Date
* Time
* Timestamp (Datetime)

## Actual

Most columns casted to strings and some (like datetime) miscasted.

## Impact

CSV files will work seemlessly. This will also empower us to infer types from SQL.

**Comment by scsmithr** [comment]
This seems done.
