### ISSUE TITLE
(mongo): Determine good chunk size when converting bson to record batches

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#724]
## Context

https://github.com/glaredb/glaredb/blob/0b27679f92851452307283cb204f9519657e6448/crates/datasource_mongodb/src/exec.rs#L143

## Expected

Chunk size is either consistent with other data sources or we pick something that's backed by performance metrics.

## Actual

Current value was arbitrarily picked.

**Comment by tychoish** [comment]
https://www.mongodb.com/docs/manual/tutorial/iterate-a-cursor/#cursor-batches <- relelvant, perhaps. 

I'm not sure what the ideal is for our end.

**Comment by tychoish** [comment]
Having thought more about this, I think the defaults are correct for our case.
