### ISSUE TITLE
Generate and update test files in GCS and S3

### ISSUE THREAD

**Issue by RustomMS** [GlareDB/glaredb#728]
## Summary
See the following scripts as an example:

https://github.com/GlareDB/glaredb/blob/main/scripts/create-test-bigquery-db.sh

and

https://github.com/GlareDB/glaredb/blob/vrongmeal/gcs-testing/scripts/create-test-gcs-db.sh

### Specifications
- Automatically update GCS and S3 parquet and csv files
- Run this during SLT CIs for GCS and S3
- Ideally allow running the script locally without uploading large files unnecessarily

## Goals
- Convenient local and CI testing for data sources that must be tested externally

**Comment by scsmithr** [comment]
This is done
