### ISSUE TITLE
Add parquet file data source testing

### ISSUE THREAD

**Issue by RustomMS** [GlareDB/glaredb#729]
## Summary
Convert bikeshare tests (e.g [csv tests](https://github.com/GlareDB/glaredb/blob/8285626200609e08d75fb7bc74144ff1e0212590/testdata/sqllogictests_object_store/local/basic.slt)) to also use the parquet format

### Specifications
- Add bike share tests
- large table slt
- a simple datatypes parquet file
## Goals
- Test to validate presentation and filtering of data in the parquet format for our object store datasources
- Easy to extend SLT tests

**Comment by scsmithr** [comment]
This is done.
