### ISSUE TITLE
(mongo): Convert simple expression filters to appropriate bson filters

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#730]
## Summary

Currently doing no filtering: https://github.com/glaredb/glaredb/blob/8285626200609e08d75fb7bc74144ff1e0212590/crates/datasource_mongodb/src/lib.rs#L121-L145

We should add support for converting simple filtering expressions to the appropriate bson document.

### Specifications

- Support simple filtering at the source

## Rationale

Reduce how much data we're sending over the network.

**Comment by universalmind303** [comment]
closing in favor of more recent #1507
