### ISSUE TITLE
Chore: Review errors when attempting to query schemas/tables that don't exist in external databases

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#851]
## Description

```
Error: test fail: query failed: db error: ERROR: Failed to dispatch to table: Failed to connect to Postgres instance: query returned an unexpected number of rows
[SQL] SELECT table_schema, table_name
	FROM external_db.virtual_datasource_schema.tables
	WHERE table_schema = 'public' AND table_name = 'bikeshare_stations';
```

`virtual_datasource_schema` doesn't exist in the external database. "Failed to connect to Postgres instance: query returned an unexpected number of rows" is not a great error.

**Comment by scsmithr** [comment]
General usability

**Comment by scsmithr** [comment]
Adding support to this. Made a failed query hard to debug.

**Comment by greyscaled** [comment]
Let's open an issue per bad error just to make it more tractable and actionable
