### ISSUE TITLE
Trigger error alert on missing catalog errors

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#995]
## Context
![image](https://github.com/GlareDB/glaredb/assets/4040560/55575097-60c5-4182-850d-25fe4c8351ba)

**Comment by scsmithr** [comment]
Another one: https://github.com/GlareDB/cloud/issues/1560

**Comment by greyscaled** [comment]
@scsmithr the picture in the ticket is messed up, can you re-upload the screenshot before you forget
